"""auto migration

Revision ID: 19ea359d47bd
Revises: ff22a270b335
Create Date: 2026-05-21 16:42:14.132766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ea359d47bd'
down_revision: Union[str, Sequence[str], None] = 'ff22a270b335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_contact_email_phone', 'contacts', ['email', 'phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contact_email_phone', table_name='contacts')
    # ### end Alembic commands ###
