"""add push tokens to contacts

Revision ID: 4a9b2c47f922
Revises: f57f236fa4eb
Create Date: 2026-04-16 22:26:56.352160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9b2c47f922'
down_revision: Union[str, Sequence[str], None] = 'f57f236fa4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('web_token', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('ios_token', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('android_token', sa.String(), nullable=True))
    op.drop_column('contacts', 'first_name')
    op.drop_column('contacts', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'android_token')
    op.drop_column('contacts', 'ios_token')
    op.drop_column('contacts', 'web_token')
    op.drop_column('contacts', 'user_name')
    # ### end Alembic commands ###
