"""add inactive_reason to contact

Revision ID: 5dd9adf2ef92
Revises: 643dd6a77ca6
Create Date: 2026-06-29 22:56:01.556414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd9adf2ef92'
down_revision: Union[str, Sequence[str], None] = '643dd6a77ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('inactive_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'inactive_reason')
    # ### end Alembic commands ###
