"""add message_id to campaign_log

Revision ID: 643dd6a77ca6
Revises: 2a9f001295e5
Create Date: 2026-06-29 22:47:13.751900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643dd6a77ca6'
down_revision: Union[str, Sequence[str], None] = '2a9f001295e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_logs', sa.Column('message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_campaign_logs_message_id'), 'campaign_logs', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_logs_message_id'), table_name='campaign_logs')
    op.drop_column('campaign_logs', 'message_id')
    # ### end Alembic commands ###
