"""add_projects_multi_tenancy

Revision ID: cb75faff8b2f
Revises: 333fa348e3d0
Create Date: 2026-04-20 21:50:51.350235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb75faff8b2f'
down_revision: Union[str, Sequence[str], None] = '333fa348e3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create Projects table
    op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('email_config', sa.JSON(), nullable=True),
        sa.Column('sms_config', sa.JSON(), nullable=True),
        sa.Column('whatsapp_config', sa.JSON(), nullable=True),
        sa.Column('push_config', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)

    # 2. Add temporary nullable project_id to existing tables
    op.add_column('campaigns', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('project_id', sa.Integer(), nullable=True))

    # 3. Create a Default Project and migrate configurations
    # We fetch existing settings to migrate them to the default project
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT email_config, sms_config, whatsapp_config, push_config FROM system_settings LIMIT 1"))
    settings = res.fetchone()
    
    default_configs = {
        "email_config": "{}",
        "sms_config": "{}",
        "whatsapp_config": "{}",
        "push_config": "{}"
    }
    
    if settings:
        # settings is a tuple, we need to handle JSON conversion if needed or just pass as is
        default_configs["email_config"] = settings[0]
        default_configs["sms_config"] = settings[1]
        default_configs["whatsapp_config"] = settings[2]
        default_configs["push_config"] = settings[3]

    # Insert default project
    import json
    conn.execute(
        sa.text("INSERT INTO projects (name, description, email_config, sms_config, whatsapp_config, push_config, created_at, updated_at) "
                "VALUES ('Default Project', 'Initial project for existing data', :e, :s, :w, :p, now(), now())"),
        {
            "e": json.dumps(default_configs["email_config"]) if isinstance(default_configs["email_config"], dict) else default_configs["email_config"], 
            "s": json.dumps(default_configs["sms_config"]) if isinstance(default_configs["sms_config"], dict) else default_configs["sms_config"], 
            "w": json.dumps(default_configs["whatsapp_config"]) if isinstance(default_configs["whatsapp_config"], dict) else default_configs["whatsapp_config"], 
            "p": json.dumps(default_configs["push_config"]) if isinstance(default_configs["push_config"], dict) else default_configs["push_config"]
        }
    )
    
    # Get the ID of the default project
    res = conn.execute(sa.text("SELECT id FROM projects WHERE name='Default Project' LIMIT 1"))
    project_id = res.scalar()

    # 4. Update existing campaigns and contacts
    conn.execute(sa.text(f"UPDATE campaigns SET project_id = {project_id}"))
    conn.execute(sa.text(f"UPDATE contacts SET project_id = {project_id}"))

    # 5. Make project_id non-nullable and add constraints
    op.alter_column('campaigns', 'project_id', nullable=False)
    op.alter_column('contacts', 'project_id', nullable=False)
    
    op.create_foreign_key('fk_campaign_project', 'campaigns', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('fk_contact_project', 'contacts', 'projects', ['project_id'], ['id'])

    # 6. Update Contact Uniqueness
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_unique_constraint('uq_contact_project_email', 'contacts', ['project_id', 'email'])
    op.create_unique_constraint('uq_contact_project_phone', 'contacts', ['project_id', 'phone'])

    # 7. Cleanup System Settings
    op.drop_column('system_settings', 'push_config')
    op.drop_column('system_settings', 'sms_config')
    op.drop_column('system_settings', 'whatsapp_config')
    op.drop_column('system_settings', 'email_config')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('email_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('system_settings', sa.Column('whatsapp_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('system_settings', sa.Column('sms_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('system_settings', sa.Column('push_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint('uq_contact_project_phone', 'contacts', type_='unique')
    op.drop_constraint('uq_contact_project_email', 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=True)
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.drop_column('contacts', 'project_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'project_id')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
