"""add_channel_configs

Revision ID: efe04dad4a0d
Revises: 45e91dd3eefa
Create Date: 2026-04-17 22:16:08.571148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe04dad4a0d'
down_revision: Union[str, Sequence[str], None] = '45e91dd3eefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('email_config', sa.JSON(), nullable=True))
    op.add_column('system_settings', sa.Column('sms_config', sa.JSON(), nullable=True))
    op.add_column('system_settings', sa.Column('whatsapp_config', sa.JSON(), nullable=True))
    op.add_column('system_settings', sa.Column('push_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'push_config')
    op.drop_column('system_settings', 'whatsapp_config')
    op.drop_column('system_settings', 'sms_config')
    op.drop_column('system_settings', 'email_config')
    # ### end Alembic commands ###
