"""add_social_and_recurring_fields

Revision ID: ff22a270b335
Revises: 17d03a81b59b
Create Date: 2026-04-28 01:25:42.752839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff22a270b335'
down_revision: Union[str, Sequence[str], None] = '17d03a81b59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_logs', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('campaigns', sa.Column('is_recurring', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('recurrence_interval', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('social_platforms', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('ai_config', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('social_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'social_config')
    op.drop_column('projects', 'ai_config')
    op.drop_column('campaigns', 'social_platforms')
    op.drop_column('campaigns', 'recurrence_interval')
    op.drop_column('campaigns', 'is_recurring')
    op.alter_column('campaign_logs', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
